---------- =============================================================================
---------- MATCHFLIX — Database Schema v5 (SQL revision 5)
---------- Oracle SQL Developer Compatible
---------- Run sections in order: 1 → 2 → 3 → 4 → 5 → 6
---------- =============================================================================
--------
--------
---------- =============================================================================
---------- SECTION 1: DROP EXISTING TABLES (safe re-run)
---------- Drop in reverse FK dependency order
---------- Note: Identity columns manage their own internal sequences — no manual
---------- sequences exist and none need to be dropped.
---------- =============================================================================
--------
--------BEGIN
--------    FOR t IN (
--------        SELECT table_name FROM user_tables
--------        WHERE table_name IN (
--------            'SOLO_RECOMMENDATIONS','SOLO_SESSION_ANSWERS','SOLO_SESSIONS',
--------            'MOVIE_RECOMMENDATIONS','SESSION_SHARED_MOVIES','MATCH_SESSIONS',
--------            'COMPATIBILITY_CACHE','USER_RATINGS','MOVIE_GENRE_MAP','GENRES',
--------            'MOVIES','USER_DIMENSION_WEIGHTS','USERS'
--------        )
--------    ) LOOP
--------        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
--------    END LOOP;
--------END;
--------
-------- =============================================================================
-------- SECTION 2: CREATE TABLES
-------- Note: GENERATED ALWAYS AS IDENTITY manages its own internal sequence.
-------- No manual sequences needed.
-------- =============================================================================
------
-------- -----------------------------------------------------------------------------
-------- 2.1  USERS
-------- Central user entity. MBTI enforced via CHECK with all 16 valid types.
-------- BOOLEAN → NUMBER(1,0) CHECK (0 or 1) in Oracle
-------- DATETIME → TIMESTAMP in Oracle
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE users (
------    user_id         NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    username        VARCHAR2(50)    NOT NULL,
------    email           VARCHAR2(120)   NOT NULL,
------    password_hash   VARCHAR2(255)   NOT NULL,
------    display_name    VARCHAR2(80),
------    age             NUMBER(3,0)     CHECK (age BETWEEN 0 AND 150),
------    mbti_type       VARCHAR2(4)     CHECK (mbti_type IN (
------                                        'INTJ','INTP','ENTJ','ENTP',
------                                        'INFJ','INFP','ENFJ','ENFP',
------                                        'ISTJ','ISFJ','ESTJ','ESFJ',
------                                        'ISTP','ISFP','ESTP','ESFP'
------                                    )),
------    avatar_url      VARCHAR2(500),
------    is_deleted      NUMBER(1,0)     DEFAULT 0 NOT NULL CHECK (is_deleted IN (0,1)),
------    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------    updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT uq_users_username    UNIQUE (username),
------    CONSTRAINT uq_users_email       UNIQUE (email)
------);
------
------COMMENT ON TABLE  users               IS 'Central user entity';
------COMMENT ON COLUMN users.mbti_type     IS 'DB-enforced ENUM of all 16 MBTI types';
------COMMENT ON COLUMN users.is_deleted    IS 'Soft delete flag — never hard delete';
------COMMENT ON COLUMN users.updated_at    IS 'Update via trigger — see SECTION 5';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.2  USER_DIMENSION_WEIGHTS
-------- One row per user per dimension (8 rows per user on signup).
-------- Replaces the JSON dimension_weights column from v1.
-------- dimension enforced via CHECK — Oracle has no ENUM type.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE user_dimension_weights (
------    weight_id   NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    user_id     NUMBER          NOT NULL,
------    dimension   VARCHAR2(30)    NOT NULL CHECK (dimension IN (
------                                    'emotional_impact','cinematography','audio_design',
------                                    'narrative_coherence','moral_conflict','thematic_depth',
------                                    'pacing','rewatch_value'
------                                )),
------    weight      NUMBER(4,2)     DEFAULT 1.00 NOT NULL CHECK (weight > 0),
------    updated_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT fk_udw_user      FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
------    CONSTRAINT uq_udw_user_dim  UNIQUE (user_id, dimension)
------);
------
------COMMENT ON TABLE  user_dimension_weights            IS 'Per-user weights for each of the 8 rating dimensions';
------COMMENT ON COLUMN user_dimension_weights.dimension  IS 'One of 8 fixed dimension keys';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.3  MOVIES
-------- Master movie catalog. language and country removed (not used in queries).
-------- runtime_minutes retained for display.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE movies (
------    movie_id            NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    title               VARCHAR2(255)   NOT NULL,
------    release_year        NUMBER(4,0)     CHECK (release_year BETWEEN 1888 AND 2100),
------    runtime_minutes     NUMBER(4,0)     CHECK (runtime_minutes > 0),
------    director            VARCHAR2(120),
------    poster_url          VARCHAR2(500),
------    synopsis            CLOB,
------    tmdb_id             NUMBER,
------    imdb_id             VARCHAR2(20),
------    is_deleted          NUMBER(1,0)     DEFAULT 0 NOT NULL CHECK (is_deleted IN (0,1)),
------    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT uq_movies_tmdb       UNIQUE (tmdb_id),
------    CONSTRAINT uq_movies_imdb       UNIQUE (imdb_id),
------    CONSTRAINT uq_movie_identity    UNIQUE (title, release_year)
------);
------
------COMMENT ON TABLE  movies            IS 'Master movie catalog — soft delete only';
------COMMENT ON COLUMN movies.synopsis   IS 'CLOB — Oracle equivalent of TEXT';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.4  GENRES
-------- Lookup table. NUMBER(3,0) sufficient for genre IDs (max ~255 genres).
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE genres (
------    genre_id    NUMBER(3,0)     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    name        VARCHAR2(60)    NOT NULL,
------
------    CONSTRAINT uq_genres_name   UNIQUE (name)
------);
------
------
-------- -----------------------------------------------------------------------------
-------- 2.5  MOVIE_GENRE_MAP
-------- M:N junction between movies and genres.
-------- Composite PK — no surrogate key needed here.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE movie_genre_map (
------    movie_id    NUMBER      NOT NULL,
------    genre_id    NUMBER(3,0) NOT NULL,
------
------    CONSTRAINT pk_movie_genre       PRIMARY KEY (movie_id, genre_id),
------    CONSTRAINT fk_mgm_movie         FOREIGN KEY (movie_id)  REFERENCES movies(movie_id) ON DELETE CASCADE,
------    CONSTRAINT fk_mgm_genre         FOREIGN KEY (genre_id)  REFERENCES genres(genre_id)
------);
------
-------- Note: Oracle uses NO ACTION (default) rather than RESTRICT — same effect.
------
------
-------- -----------------------------------------------------------------------------
-------- 2.6  USER_RATINGS
-------- Core of the rating engine. All 8 dimensions enforced with CHECK constraints.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE user_ratings (
------    rating_id           NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    user_id             NUMBER          NOT NULL,
------    movie_id            NUMBER          NOT NULL,
------
------    -- 8 psychological dimensions — all enforced 1.00–10.00
------    emotional_impact    NUMBER(4,2)     NOT NULL CHECK (emotional_impact    BETWEEN 1.00 AND 10.00),
------    cinematography      NUMBER(4,2)     NOT NULL CHECK (cinematography      BETWEEN 1.00 AND 10.00),
------    audio_design        NUMBER(4,2)     NOT NULL CHECK (audio_design        BETWEEN 1.00 AND 10.00),
------    narrative_coherence NUMBER(4,2)     NOT NULL CHECK (narrative_coherence BETWEEN 1.00 AND 10.00),
------    moral_conflict      NUMBER(4,2)     NOT NULL CHECK (moral_conflict      BETWEEN 1.00 AND 10.00),
------    thematic_depth      NUMBER(4,2)     NOT NULL CHECK (thematic_depth      BETWEEN 1.00 AND 10.00),
------    pacing              NUMBER(4,2)     NOT NULL CHECK (pacing              BETWEEN 1.00 AND 10.00),
------    rewatch_value       NUMBER(4,2)     NOT NULL CHECK (rewatch_value       BETWEEN 1.00 AND 10.00),
------
------    overall_score       NUMBER(4,2)     CHECK (overall_score BETWEEN 1.00 AND 10.00),
------    review_text         CLOB,
------    watched_at          DATE,
------    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------    updated_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT fk_ur_user           FOREIGN KEY (user_id)   REFERENCES users(user_id)   ON DELETE CASCADE,
------    CONSTRAINT fk_ur_movie          FOREIGN KEY (movie_id)  REFERENCES movies(movie_id),
------    CONSTRAINT uq_ur_user_movie     UNIQUE (user_id, movie_id)
------);
------
------COMMENT ON TABLE  user_ratings                  IS 'Core rating engine — one row per user per movie';
------COMMENT ON COLUMN user_ratings.overall_score    IS 'Optional — separate from the 8 dimension scores';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.7  COMPATIBILITY_CACHE
-------- Precomputed compatibility between two users.
-------- user_a_id < user_b_id enforced via CHECK constraint (chk_cc_user_order).
-------- JSON → CLOB with IS JSON constraint (Oracle 12c+).
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE compatibility_cache (
------    cache_id            NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    user_a_id           NUMBER          NOT NULL,
------    user_b_id           NUMBER          NOT NULL,
------
------    -- Overall and per-dimension alignment scores (0.0000 – 1.0000)
------    overall_score       NUMBER(5,4)     NOT NULL CHECK (overall_score       BETWEEN 0 AND 1),
------    emotional_align     NUMBER(5,4)     NOT NULL CHECK (emotional_align     BETWEEN 0 AND 1),
------    cinematography_align NUMBER(5,4)   NOT NULL CHECK (cinematography_align BETWEEN 0 AND 1),
------    audio_align         NUMBER(5,4)     NOT NULL CHECK (audio_align         BETWEEN 0 AND 1),
------    narrative_align     NUMBER(5,4)     NOT NULL CHECK (narrative_align     BETWEEN 0 AND 1),
------    moral_align         NUMBER(5,4)     NOT NULL CHECK (moral_align         BETWEEN 0 AND 1),
------    thematic_align      NUMBER(5,4)     NOT NULL CHECK (thematic_align      BETWEEN 0 AND 1),
------    pacing_align        NUMBER(5,4)     NOT NULL CHECK (pacing_align        BETWEEN 0 AND 1),
------    rewatch_align       NUMBER(5,4)     NOT NULL CHECK (rewatch_align       BETWEEN 0 AND 1),
------
------    most_aligned_dim    VARCHAR2(30)    CHECK (most_aligned_dim IN (
------                                            'emotional_impact','cinematography','audio_design',
------                                            'narrative_coherence','moral_conflict','thematic_depth',
------                                            'pacing','rewatch_value'
------                                        )),
------    least_aligned_dim   VARCHAR2(30)    CHECK (least_aligned_dim IN (
------                                            'emotional_impact','cinematography','audio_design',
------                                            'narrative_coherence','moral_conflict','thematic_depth',
------                                            'pacing','rewatch_value'
------                                        )),
------    shared_movie_count  NUMBER(5,0)     DEFAULT 0 NOT NULL,
------    is_stale            NUMBER(1,0)     DEFAULT 0 NOT NULL CHECK (is_stale IN (0,1)),
------    archetype           VARCHAR2(60),
------    conflict_triggers   CLOB            CHECK (conflict_triggers IS JSON),
------    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------    calculated_at       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT fk_cc_user_a         FOREIGN KEY (user_a_id) REFERENCES users(user_id) ON DELETE CASCADE,
------    CONSTRAINT fk_cc_user_b         FOREIGN KEY (user_b_id) REFERENCES users(user_id) ON DELETE CASCADE,
------    CONSTRAINT uq_cc_pair           UNIQUE (user_a_id, user_b_id),
------    CONSTRAINT chk_cc_user_order    CHECK (user_a_id < user_b_id)
------);
------
------COMMENT ON COLUMN compatibility_cache.conflict_triggers IS 'JSON array of dimension keys where gap > 6, e.g. ["moral_conflict","pacing"]';
------COMMENT ON COLUMN compatibility_cache.created_at        IS 'First creation — distinct from calculated_at which updates on recalc';
------COMMENT ON COLUMN compatibility_cache.is_stale          IS '1 = needs background recalculation';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.8  MATCH_SESSIONS
-------- One record per compatibility session. Separate from cache — allows history.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE match_sessions (
------    session_id          NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    initiated_by        NUMBER          NOT NULL,
------    matched_with        NUMBER          NOT NULL,
------    compatibility_score NUMBER(5,4)     NOT NULL CHECK (compatibility_score BETWEEN 0 AND 1),
------    archetype           VARCHAR2(60),
------    conflict_triggers   CLOB            CHECK (conflict_triggers IS JSON),
------    most_aligned_dim    VARCHAR2(30)    CHECK (most_aligned_dim IN (
------                                            'emotional_impact','cinematography','audio_design',
------                                            'narrative_coherence','moral_conflict','thematic_depth',
------                                            'pacing','rewatch_value'
------                                        )),
------    least_aligned_dim   VARCHAR2(30)    CHECK (least_aligned_dim IN (
------                                            'emotional_impact','cinematography','audio_design',
------                                            'narrative_coherence','moral_conflict','thematic_depth',
------                                            'pacing','rewatch_value'
------                                        )),
------    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT fk_ms_initiator      FOREIGN KEY (initiated_by)  REFERENCES users(user_id) ON DELETE CASCADE,
------    CONSTRAINT fk_ms_matched        FOREIGN KEY (matched_with)  REFERENCES users(user_id) ON DELETE CASCADE
------);
------
------COMMENT ON COLUMN match_sessions.conflict_triggers IS 'JSON array — dims where pair gap > 6';
------COMMENT ON COLUMN match_sessions.archetype         IS 'e.g. The Philosophers, The Technicians';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.9  SESSION_SHARED_MOVIES
-------- Junction table — replaces top_shared_movie_1/2/3 (1NF fix).
-------- Stores top shared favorite movies per match session.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE session_shared_movies (
------    id          NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    session_id  NUMBER          NOT NULL,
------    movie_id    NUMBER          NOT NULL,
------    rank        NUMBER(2,0)     NOT NULL CHECK (rank BETWEEN 1 AND 10),
------
------    CONSTRAINT fk_ssm_session       FOREIGN KEY (session_id)    REFERENCES match_sessions(session_id)   ON DELETE CASCADE,
------    CONSTRAINT fk_ssm_movie         FOREIGN KEY (movie_id)      REFERENCES movies(movie_id),
------    CONSTRAINT uq_ssm_session_rank  UNIQUE (session_id, rank),
------    CONSTRAINT uq_ssm_session_movie UNIQUE (session_id, movie_id)
------);
------
------COMMENT ON TABLE session_shared_movies IS 'Replaces top_shared_movie_1/2/3 — normalised junction table';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.10  MOVIE_RECOMMENDATIONS
-------- 5 recommended movies per match session.
-------- reason_code and conflict_flags stored here for per-card UI display.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE movie_recommendations (
------    rec_id          NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    session_id      NUMBER          NOT NULL,
------    movie_id        NUMBER          NOT NULL,
------    rank            NUMBER(1,0)     NOT NULL CHECK (rank BETWEEN 1 AND 5),
------    reason_code     VARCHAR2(20)    NOT NULL CHECK (reason_code IN (
------                                        'UNWATCHED','SIMILAR_USERS','TOP_ALIGNED'
------                                    )),
------    conflict_flags  CLOB            CHECK (conflict_flags IS JSON),
------    score           NUMBER(5,4)     NOT NULL CHECK (score BETWEEN 0 AND 1),
------    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT fk_mr_session        FOREIGN KEY (session_id)    REFERENCES match_sessions(session_id)   ON DELETE CASCADE,
------    CONSTRAINT fk_mr_movie          FOREIGN KEY (movie_id)      REFERENCES movies(movie_id)             ON DELETE CASCADE,
------    CONSTRAINT uq_mr_session_rank   UNIQUE (session_id, rank)
------);
------
------COMMENT ON COLUMN movie_recommendations.conflict_flags IS 'JSON array — subset of pair conflict_triggers relevant to this movie';
------COMMENT ON COLUMN movie_recommendations.reason_code    IS 'UNWATCHED | SIMILAR_USERS | TOP_ALIGNED';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.11  SOLO_SESSIONS
-------- Tracks a single user smart finder session.
-------- filter_weights = Q&A-derived dimension weights (JSON)
-------- dimension_filters = slider-based threshold filters (JSON)
-------- Discovery-first: no year/runtime/language filters.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE solo_sessions (
------    session_id          NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    user_id             NUMBER          NOT NULL,
------    filter_weights      CLOB            NOT NULL CHECK (filter_weights IS JSON),
------    dimension_filters   CLOB            CHECK (dimension_filters IS JSON),
------    genre_filter        CLOB            CHECK (genre_filter IS JSON),
------    mood_tag            VARCHAR2(60),
------    status              VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL CHECK (status IN (
------                                            'ACTIVE','COMPLETED','EXPIRED'
------                                        )),
------    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------    completed_at        TIMESTAMP,
------
------    CONSTRAINT fk_ss_user           FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
------);
------
------COMMENT ON COLUMN solo_sessions.filter_weights    IS 'QnA-derived weights e.g. {"pacing": 1.5, "thematic_depth": 1.2}';
------COMMENT ON COLUMN solo_sessions.dimension_filters IS 'Slider thresholds e.g. {"pacing": {"min": 7}, "thematic_depth": {"min": 6, "max": 9}}';
------COMMENT ON COLUMN solo_sessions.genre_filter      IS 'JSON array of genre_id values e.g. [1, 4, 7]';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.12  SOLO_SESSION_ANSWERS
-------- Audit trail of individual Q&A answers per session.
-------- Enables re-processing if question weight logic changes.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE solo_session_answers (
------    answer_id           NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    session_id          NUMBER          NOT NULL,
------    question_key        VARCHAR2(60)    NOT NULL,
------    question_text       VARCHAR2(500)   NOT NULL,
------    answer_value        VARCHAR2(120)   NOT NULL,
------    weight_contribution CLOB            CHECK (weight_contribution IS JSON),
------    answered_at         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT fk_ssa_session       FOREIGN KEY (session_id) REFERENCES solo_sessions(session_id) ON DELETE CASCADE
------);
------
------COMMENT ON COLUMN solo_session_answers.weight_contribution IS 'JSON — how this answer modified filter_weights';
------
------
-------- -----------------------------------------------------------------------------
-------- 2.13  SOLO_RECOMMENDATIONS
-------- Top 3–10 results per solo session.
-------- randomization_seed enables different top-3 on repeat runs.
-------- -----------------------------------------------------------------------------
------
------CREATE TABLE solo_recommendations (
------    rec_id              NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
------    session_id          NUMBER          NOT NULL,
------    movie_id            NUMBER          NOT NULL,
------    rank                NUMBER(2,0)     NOT NULL CHECK (rank BETWEEN 1 AND 10),
------    final_score         NUMBER(5,4)     NOT NULL CHECK (final_score BETWEEN 0 AND 1),
------    shown_to_user       NUMBER(1,0)     DEFAULT 0 NOT NULL CHECK (shown_to_user IN (0,1)),
------    randomization_seed  NUMBER(10,0),
------    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
------
------    CONSTRAINT fk_sr_session        FOREIGN KEY (session_id)    REFERENCES solo_sessions(session_id)    ON DELETE CASCADE,
------    CONSTRAINT fk_sr_movie          FOREIGN KEY (movie_id)      REFERENCES movies(movie_id)             ON DELETE CASCADE,
------    CONSTRAINT uq_sr_session_rank   UNIQUE (session_id, rank),
------    CONSTRAINT uq_sr_session_movie  UNIQUE (session_id, movie_id)
------);
------
------COMMENT ON COLUMN solo_recommendations.shown_to_user      IS '1 = displayed in final top 3 to user';
------COMMENT ON COLUMN solo_recommendations.randomization_seed IS 'Seed used for shuffle — enables reproducible results';
----
------ =============================================================================
------ SECTION 3: INDEXES
------ UNIQUE constraints already create backing indexes automatically in Oracle.
------ Only non-constraint indexes are listed here to avoid duplication.
------ Removed (already backed by UNIQUE constraint):
------   idx_users_email, idx_users_username  → uq_users_email, uq_users_username
------   idx_udw_user_dim                     → uq_udw_user_dim
------   idx_ur_user_movie                    → uq_ur_user_movie
------   idx_cc_pair                          → uq_cc_pair
------   idx_ssm_rank                         → uq_ssm_session_rank
------ =============================================================================
----
------ users — soft-delete filtering
----CREATE INDEX idx_users_deleted          ON users (is_deleted, user_id);
----
------ movies — title search + soft-delete filtering
----CREATE INDEX idx_movies_title           ON movies (title);
----CREATE INDEX idx_movies_deleted         ON movies (is_deleted, movie_id);
----
------ movie_genre_map — genre-first lookups (composite PK covers movie-first)
----CREATE INDEX idx_mgm_genre              ON movie_genre_map (genre_id);
----
------ user_ratings — aggregate by movie / fetch by user
----CREATE INDEX idx_ur_movie               ON user_ratings (movie_id);
----CREATE INDEX idx_ur_user                ON user_ratings (user_id);
----
------ compatibility_cache — background recalc queue
----CREATE INDEX idx_cc_stale               ON compatibility_cache (is_stale, calculated_at);
----
------ match_sessions — session history lookup
----CREATE INDEX idx_ms_users               ON match_sessions (initiated_by, matched_with);
----
------ movie_recommendations — fetch all recs for a session
----CREATE INDEX idx_mr_session             ON movie_recommendations (session_id);
----
------ solo_sessions — active session check per user
----CREATE INDEX idx_ss_user_status         ON solo_sessions (user_id, status);
----
------ solo_recommendations — displayed results fetch
----CREATE INDEX idx_sr_session_shown       ON solo_recommendations (session_id, shown_to_user);
--
---- =============================================================================
---- SECTION 4: TRIGGERS
---- Oracle requires triggers to handle updated_at timestamps
---- (no ON UPDATE CURRENT_TIMESTAMP like MySQL).
---- SYSTIMESTAMP used instead of CURRENT_TIMESTAMP for sub-millisecond precision.
---- =============================================================================
--
--CREATE OR REPLACE TRIGGER trg_users_updated_at
--    BEFORE UPDATE ON users
--    FOR EACH ROW
--BEGIN
--    :NEW.updated_at := SYSTIMESTAMP;
--END;
--/
--
--CREATE OR REPLACE TRIGGER trg_ur_updated_at
--    BEFORE UPDATE ON user_ratings
--    FOR EACH ROW
--BEGIN
--    :NEW.updated_at := SYSTIMESTAMP;
--END;
--/
--
--CREATE OR REPLACE TRIGGER trg_udw_updated_at
--    BEFORE UPDATE ON user_dimension_weights
--    FOR EACH ROW
--BEGIN
--    :NEW.updated_at := SYSTIMESTAMP;
--END;
--/

